name: API ETL Pipeline

on:
  push:
    branches:
      - main
  
jobs:
    read-from-api:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.14.0'

          - name: Install dependencies
            run: pip install -r requirements.txt
              

          - name: get data from API
            env:
              API_TOKEN: ${{ secrets.API_TOKEN }}
            run: |
                 cd .github/workflows
                 python read_data_api.py